### PR TITLE
Just some things I added that people might find useful

### LINKED ISSUE #8: Please add explode, reroll
I'd love to use this library but I can't use it without the features of explode and reroll. I see these feature present in https://github.com/borntyping-sandbox/diceroll but they never seemed to make it over to this version.

Was there a specific reasoning on not porting this over?

### LINKED ISSUE #9: Possible to roll a negative number
I have wrapped this library using [legos.dice](https://pypi.python.org/pypi/legos.dice) for use in a chatbot. In my module, we merely grab the roll value and pass it straight to a call do `dice`. 

One of my users just discovered this fun bug:

```
│“19:11”                              ⤷ ╡ !roll -1d42                                                                                                                   │
│“19:11”                MissMoneyPenney ╡ You Rolled: -29
```

### LINKED ISSUE #10: `3d6^2s` raises, `3d6^2t` doesn't total.
Noticed a slight discrepancy here, at least from user standpoint.
`3d6^2t` doesn't error, but it doesn't total the result either. `3d6^2s` errors with `AttributeError: 'Integer' object has no attribute 'sort'`.

Possible solution could be to just strip t/s off the end, evaluate, then total/sort?

### PR DESCRIPTION
**Pull request by calebj**
* Wild dice (`NwS`): Last die rolled is the "wild die". If its last roll is...
  * max: explode recursively
  * min: set and the highest value to the lowest possible, then reroll. If min again, critfail (all min).
* Fudge dice (`dF` for range of -1 to 1, `NuR` for range of -R to R)
* Percentile dice (`d%`) shortcut
* Additional operators (all case insensitive):
  * Successes (`e`)
  * Successes minus failures (`f`)
  * Middle (`o`, `m`)
    * Defaults to dropping single highest and lowest.
  * Unary negative and positive
    * Handles stray `+` signs
    * Unary negative operates on both vectors or scalars
  * Explode (`x`), reroll (`r`) and recursive reroll (`rr`)
    * Requested in borntyping/python-dice#8
    * Operand defaults to max and min respectively
  * Multiple rolls (`,`)
    * Coerces operands to scalars
  * Build vector / "concatenate" (`|`)
    * Coerces/encapsulates operands into a vector
  * Pointwise add/subtract (`.+`, `.-`)
    * adds or subtracts from all elements. `[1, 2, 3] .+ 4` => `[5, 6, 7]`
* Expose min and max possible result of rolls
* Roll result introspection/breakdown via command line and API
  * Can output unevaluated expression and evaluate with cache disabled
* Tests
  * More Python versions and passes on Travis
  * More exhaustive tests, including of new operators
  * Known bad expressions checked for raised exceptions
* Documentation
* Command line:
  * Args for forcing min and max rolls
  * Verbose outputs result breakdown
  * Module invocation (`python -m dice <options>`)
  * Use `--` to allow expressions that start with a minus sign
* Cap maximum number of dice rolled (can crash if sorting too many)
* Speed improvement for low/mid/high operators
* Tweaked drop and keep:
  * Keep (highest) is now [`^`, `h`] and drop (lowest) is [`v`, `l`]
  * Both default to n-1, which drops the single highest or lowest respectively
* Correct add even/sub odd implementation, and keep result as a vector
  * Fix for borntyping/python-dice#9
* Raise parsing exception for `d0`, as mentioned in borntyping-sandbox/diceroll#3
* Version bump and credits

Resolves #8, closes #9, and fixes #10.

### CODE REVIEW

**Comment by borntyping** [comment]
This looks great! I'll try and read though it tonight and get it merged.

**Comment by borntyping** [comment]
Released as version `2.0.0` :tada: 

If you're interested in being a maintainer for this project, I'd be happy to add you as a collaborator on this repo and the pypi package - even if you aren't, huge thanks for putting so much work into this!

**Comment by calebj** [comment]
Sure, I'd love to! I was hesitant to put the 2.0.0 label on it since you were using that in the sandbox version, but it looks like this has superseded it! I'm quite flattered.

**Comment by borntyping** [comment]
The [diceroll](https://github.com/borntyping/diceroll) repo is a mostly separate project that was built before this, so the version number is unrelated.

Have you got a username on PyPi I can add to the package?

**Comment by calebj** [comment]
Ah, I see. I do have a PyPi username; it's the same as it is here, `calebj`.

**Pull request merged**
